language: go

go:
  - 1.15.x

install: true

jobs:
  include:
    - stage: "Compile"
      name: "Compile Packages and Dependencies"
      script: make build

    - stage: "Tests"
      name: "Unit Tests"
      script: make test

    - stage: "Code Quality"
      name: "Code Quality Analysis"
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.28.3
      script: golangci-lint run

    - stage: "Integration Tests"
      name: "Integration Tests"