language: go

go:
  - 1.15.x

notifications:
  email: false

env:
  global:
    - GO111MODULE=on

jobs:
  include:
    - stage: "Compile"
      name: "Compile Packages and Dependencies"
      script: make build

    - stage: "Code Quality"
      name: "Linters"
      install: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.32.2
      script: golangci-lint run ./...

    - stage: "Tests"
      name: "Unit Tests"
      script: make test

    - stage: "Integration Tests"
      name: "Integration Tests"
      script: make itest