version: "3.3"

services:
  bouncer:
    container_name: bouncer
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    environment:
      - CONFIG_PATH=./config.yaml

  integration-tests:
    image: golang:1.15
    volumes:
      - ./:/app/
    working_dir: /app
    command: sh -c 'go test -v ./tests/...'
    depends_on:
      - bouncer