version: "3.4"

services:
  bouncer:
    container_name: bouncer
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
    - CONFIG_PATH=./config.yaml